deployment:
  env:
    INVENTORY_SERVICE: inventory:80
    JAEGER_HOST: jaeger-agent.istio-system.svc.cluster.local
    JAEGER_PORT: 6832
ingress:
  enabled: true
port: 8080
secrets:
  env:
    enabled: true
    name: initiation-camunda-client-env
  config:
    enabled: true
    name: initiation-camunda-client-config
    mountpath: /usr/src/app/config/env/development.json
    subpath: development.json
