deployment:
  image:
    repository: 002665144501.dkr.ecr.eu-central-1.amazonaws.com/bf-api-initiation-camunda-client
  env:
    ENVIRONMENT: dev
hostName: camunda-client.bridgefund-development.net
#deployment
